name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Prisma Generate
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
